### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by deepu105** [nodesource/npmsearch#37]
The website http://npmsearch.com/ seems to be down

**Comment by tmpvar** [comment]
looks like ramnode turned the box off as elasticsearch was using too much CPU... investigating

**Comment by fisch0920** [comment]
it seems to be working intermittently for me; when it fails, it's because of a failed websocket handshake

**Comment by JoeDoyle23** [comment]
npmsearch.com is now running on better hardware and should be more stable.
