### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by pbakondy** [nodesource/npmsearch#42]
First issue: the website does not list this package:
https://npmsearch.com/?q=cordova-plugin-speechrecognition
This is essential for cordova packages site.

Originial:
https://www.npmjs.com/package/cordova-plugin-speechrecognition

Second issue:
The site does not list all of my packages (13 of 17):
https://npmsearch.com/?q=author:pbakondy

**Comment by BlueSialia** [comment]
Also happening with https://npmsearch.com/?q=cocoon-plugin-ads-ios-admob and others packages with similar name cocoon-plugin-ads-ios-admob-\<thingy> (only one appears).

Likewise, it doesn't list all my packages https://npmsearch.com/?q=author:ludei (54 of 69).

**Comment by tmpvar** [comment]
Looks like an elasticsearch shard became corrupted. I'm doing a full re-index now because I have no idea what the last valid npm sequence was.

The new index should be ready to go in ~30m

**Comment by BlueSialia** [comment]
Now it only list 22 of 69 packages in https://npmsearch.com/?q=author:ludei

**Comment by BlueSialia** [comment]
Now looks like it is fixed. I see all my packages at least.

Thanks!

**Comment by pbakondy** [comment]
ok

**Comment by BlueSialia** [comment]
Hello,

I think this should be reopened. There are missing packages again. 71 packages at https://www.npmjs.com/~ludei and only 53 at https://npmsearch.com/?q=author:ludei.

**Comment by pbakondy** [comment]
agree

**Comment by JoeDoyle23** [comment]
I just checked now and I see 71 at https://npmsearch.com/?q=author:ludei. We'll see if there is anything showing up as errors to see what's causing the delay.

**Comment by BlueSialia** [comment]
Agree, now I see 71 too. Looks like this issue happens very intermittently.

**Comment by jdubois** [comment]
This should be re-opened, I have the same problem when doing:

https://npmsearch.com/query?fields=name,keywords,description,author,homepage,version,repository,created&q=keywords:jhipster-module&from=0&size=100

You can see this live on the JHipster website: https://jhipster.github.io/modules/marketplace/#/list

We only see 10 results, when there are 31 packages with this keyword, see for example here: https://npms.io/search?q=jhipster-module

Linking to our ticket: https://github.com/jhipster/generator-jhipster/issues/4866

**Comment by tmpvar** [comment]
@jdubois I'm seeing 32 now

**Comment by jdubois** [comment]
@tmpvar yes, we moved to npms.io
