### ISSUE TITLE
Search missing results

### ISSUE THREAD

**Issue by sunnycupertino** [nodesource/npmsearch#45]
Hi. The search index doesn't seem to contain various packages anymore, for example https://github.com/sunnycupertino/cordova-plugin-admob-simple
https://www.npmjs.com/package/cordova-plugin-admob-simple

If you search here https://npmsearch.com/?q=keywords:admob , it doesn't show up, but used to.

**Comment by tmpvar** [comment]
Looks like a hiccup - it's there now


<img width="1173" alt="screen shot 2017-01-17 at 3 06 09 pm" src="https://cloud.githubusercontent.com/assets/46673/22037762/8397a3f6-dcc6-11e6-8f65-a99f27d590ee.png">

**Comment by sunnycupertino** [comment]
We just updated the version number and I think that brought it back, but it had been like that (disappeared) for quite a while.....
